apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-nginx
  name: frontend-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
        - image: 771031500557.dkr.ecr.ap-northeast-2.amazonaws.com/k8s-cluster-repo:v1.0
          name: frontend-nginx
